{{- if .Values.global.deploy.mysql }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: dview/mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
          args:
            - --server-id=1
            - --log-bin=mysql-bin
            - --binlog-format=ROW
            - --binlog-row-image=FULL
            - --log-bin-trust-function-creators=1
            - --expire-logs-days=7
            - --default-authentication-plugin=mysql_native_password
            - --max-connections=1024
            - --innodb_file_per_table=true
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: init-scripts
          configMap:
            name: mysql-init-scripts
  {{- end }}