{{- if and .Values.global.deploy.mysql .Values.global.virtualService.deploy .Values.global.virtualService.mysql.required }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mysql-vs
spec:
  hosts:
  - {{ .Values.global.virtualService.mysql.hosts }}
  gateways:
  - {{ .Values.global.virtualService.gateways }}
  http:
  - route:
    - destination:
        host: mysql
        port:
          number: 3306
{{- end }}