apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-monitor-role
  namespace: automation
rules:
- apiGroups: [""]
  resources: ["pods", "events"]
  verbs: ["get", "watch", "list"]