{{- if .Values.global.deploy.apollo }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: apollo
    k8s-app: apollo
  name: apollo
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: {{ .Values.global.service.apollo.app.port | default 80 }}
    - name: https
      port: 443
      protocol: TCP
      targetPort: {{ .Values.global.service.apollo.app.port | default 80 }}
  selector:
    k8s-app: apollo
  sessionAffinity: None
  type: ClusterIP
{{- end }}