{{- if and .Values.global.deploy.trino .Values.global.virtualService.deploy .Values.global.virtualService.trino.required }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: trino-vs
spec:
  hosts:
  - {{ .Values.global.virtualService.trino.hosts }}
  gateways:
  - {{ .Values.global.virtualService.gateways }}
  http:
  - route:
    - destination:
        host: trino
{{- end }}