# Source: neo4j/templates/neo4j-serviceaccount.yaml
# ClusterIP service for bolt / http connections
apiVersion: v1
kind: Service
metadata:
  name: "neo4j"
  labels:
    helm.neo4j.com/neo4j.name: "neo4j"
    app: "neo4j"
    helm.neo4j.com/instance: "neo4j"
    helm.neo4j.com/service: "default"
spec:
  publishNotReadyAddresses: false
  type: ClusterIP
  selector:
    app: "neo4j"
    helm.neo4j.com/instance: "neo4j"
  ports:
    - protocol: TCP
      port: 7687
      targetPort: 7687
      name: tcp-bolt
    - protocol: TCP
      port: 7474
      targetPort: 7474
      name: tcp-http