{{ if .Values.global.deploy.airflow }}
apiVersion: v1
kind: Service
metadata:
  name: airflow
spec:
  ports:
  - port: {{ .Values.global.service.airflow.app.port | default 80 }}
    targetPort: {{ .Values.global.service.airflow.app.port | default 80 }}
    protocol: TCP
  selector:
    app: airflow
{{ end }}