{{- if and .Values.global.virtualService.deploy .Values.global.virtualService.airflow.required .Values.global.deploy.airflow }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: airflow-vs
spec:
  hosts:
  - {{ .Values.global.virtualService.airflow.hosts }}
  gateways:
  - {{ .Values.global.virtualService.gateways }}
  http:
  - route:
    - destination:
        host: airflow-webserver
{{ end }}