{{- if and .Values.global.deploy.artemis .Values.global.service.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: artemis-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: artemis
  minReplicas: {{ .Values.global.service.autoscaling.minReplicas | default 1 }}
  maxReplicas: {{ .Values.global.service.autoscaling.maxReplicas | default 1 }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.global.service.autoscaling.averageCpuUtilization | default 70 }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.global.service.autoscaling.averageMemoryUtilization | default 70 }}
{{- end }}