{{- if and .Values.global.virtualService.deploy .Values.global.virtualService.cosmos.required .Values.global.deploy.cosmos }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: cosmos-virtual-svc
spec:
  gateways:
    - {{ .Values.global.virtualService.gateways | quote }}
  hosts:
    - {{ .Values.global.virtualService.cosmos.hosts | quote }}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: cosmos
            port:
              number: 80
{{- end }}