apiVersion: v1
kind: ServiceAccount
metadata:
  name: trino
  labels:
    helm.sh/chart: trino-0.14.0
    app.kubernetes.io/name: trino
    app.kubernetes.io/instance: trino
    app.kubernetes.io/version: "432"
    app.kubernetes.io/managed-by: Helm