{{- if and .Values.global.deploy.redis .Values.global.service.redis.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.global.service.redis.pvc.size }}
{{- end }}