{{- if and .Values.global.deploy.redis .Values.global.virtualService.deploy .Values.global.virtualService.redis.required }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: redis-vs
spec:
  hosts:
  - {{ .Values.global.virtualService.redis.hosts }}
  gateways:
  - {{ .Values.global.virtualService.gateways }}
  http:
  - route:
    - destination:
        host: redis
{{- end }}