{{- if .Values.global.deploy.kafka }}
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  ports:
  - port: {{ .Values.global.service.kafka.app.port | default 80 }}
    targetPort: {{ .Values.global.service.kafka.app.port | default 80 }}
    protocol: TCP
  selector:
    app: kafka
{{- end }}