image:
  repository: dview/trino
  pullPolicy: Always
  tag: 469
imagePullSecrets: []
server:
  workers: 1
  node:
    environment: production
    dataDir: /data/trino
    pluginDir: /usr/lib/trino/plugin
  log:
    trino:
      level: INFO
  config:
    path: /etc/trino
    mountPath: /mnt/etc/trino
    http:
      port: 8080
    https:
      enabled: false
      port: 8443
      keystore:
        path: ''
    authenticationType: ''
    query:
      maxMemory: 4GB
  exchangeManager:
    name: filesystem
    baseDir: /tmp/trino-local-file-system-exchange-manager
  workerExtraConfig: ''
  coordinatorExtraConfig: ''
  autoscaling:
    enabled: false
    maxReplicas: 5
    targetCPUUtilizationPercentage: 50
accessControl: {}
additionalNodeProperties: {}
additionalConfigProperties: {}
additionalLogProperties: {}
additionalExchangeManagerProperties: {}
eventListenerProperties: {}
additionalCatalogs:
  sms: |-
    connector.name=kafka
    kafka.nodes=kafka:9092
    kafka.table-description-supplier=FILE
    kafka.table-description-dir=/mnt/data/repo/schemas/repo/schemas
    kafka.default-schema=
    kafka.hide-internal-columns=true
    kafka.table-names=
  adhoc: |-
    connector.name=hive
    hive.metastore.uri=thrift://hive-metastore:9083
    hive.metastore-cache-ttl=20m
    hive.metastore-refresh-interval=10m
    hive.metastore.thrift.client.connect-timeout=30m
    hive.metastore.thrift.client.read-timeout=30m
    hive.orc.use-column-names=true
    hive.parquet.use-column-names=true
    hive.non-managed-table-writes-enabled=true
    hive.recursive-directories=true
    hive.ignore-absent-partitions=true
    hive.metastore.thrift.delete-files-on-drop=true
    hive.compression-codec=ZSTD
    fs.native-s3.enabled=true
env:
- name: TRINO_MOUNT_CONFIG_PATH
  value: /mnt/etc/trino
- name: TRINO_CONFIG_PATH
  value: /etc/
- name: AWS_ACCESS_KEY
  value: null
- name: accessKey
  value: null
- name: secretKey
  value: null
- name: AWS_SECRET_KEY
  value: null
envFrom: []
initContainers: {}
sidecarContainers: {}
securityContext:
  runAsUser: 0
  runAsGroup: 0
shareProcessNamespace:
  coordinator: false
  worker: false
service:
  type: ClusterIP
  port: 8080
auth: {}
serviceAccount:
  create: false
  name: ''
  annotations: {}
secretMounts: []
coordinator:
  jvm:
    maxHeapSize: 8G
    gcMethod:
      type: UseG1GC
      g1:
        heapRegionSize: 32M
  config:
    memory:
      heapHeadroomPerNode: ''
    query:
      maxMemoryPerNode: 1GB
  additionalJVMConfig: {}
  additionalExposedPorts: {}
  resources: {}
  livenessProbe: {}
  readinessProbe: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  additionalConfigFiles: {}
  annotations: {}
  labels: {}
  secretMounts: []
worker:
  jvm:
    maxHeapSize: 8G
    gcMethod:
      type: UseG1GC
      g1:
        heapRegionSize: 32M
  config:
    memory:
      heapHeadroomPerNode: ''
    query:
      maxMemoryPerNode: 1GB
  additionalJVMConfig: {}
  additionalExposedPorts: {}
  resources: {}
  livenessProbe: {}
  readinessProbe: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  additionalConfigFiles: {}
  annotations: {}
  labels: {}
  secretMounts: []
kafka:
  mountPath: /mnt/etc/trino/schemas
  tableDescriptions: {}
commonLabels: {}
ingress:
  enabled: false
  className: ''
  annotations: {}
  hosts: []
  tls: []
ranger:
  enabled: true
  policy_manager_url: http://ranger-admin:6080
  repository_name: aqua
  elasticsearch:
    enabled: false
  mountPath: /mnt/ranger/
vs:
  enabled: true
git_sync:
  enabled: true
currentTimeStamp: '2025-01-28T19:20:07.956322824Z'
mysql:
  host: mysql
  port: 3306
  user: root
  password: root