{{- if and .Values.global.deploy.hive .Values.global.virtualService.deploy .Values.global.virtualService.hive.required }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hive-vs
spec:
  hosts:
  - {{ .Values.global.virtualService.hive.hosts }}
  gateways:
  - {{ .Values.global.virtualService.gateways }}
  http:
  - route:
    - destination:
        host: hive
{{- end }}