{{- if and .Values.global.virtualService.deploy .Values.global.virtualService.jobweaver.dbt.required .Values.global.deploy.jobweaver }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dbt-docs-vs
spec:
  hosts:
    - {{ .Values.global.virtualService.jobweaver.dbt.hosts | quote }}
  gateways:
    - {{ .Values.global.virtualService.gateways | quote }}
  http:
    - route:
        - destination:
            host: jobweaver
            port:
              number: {{ .Values.global.service.jobweaver.app.dbt.lineagePort | default 8080 }}
{{- end }}