{{- if and .Values.global.virtualService.deploy .Values.global.virtualService.trinity.required .Values.global.deploy.trinity }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: trinity-virtual-svc
spec:
  gateways:
    - {{ .Values.global.virtualService.gateways | quote }}
  hosts:
    - {{ .Values.global.virtualService.trinity.hosts | quote }}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: trinity
            port:
              number: 80
{{- end }}