{{- if .Values.global.deploy.cerebrum }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: cerebrum
  name: cerebrum
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.global.service.cerebrum.app.replicas | default .Values.global.service.replicas }} 
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: cerebrum
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: cerebrum
    spec:
      terminationGracePeriodSeconds: {{ .Values.global.service.terminationGracePeriodSeconds | default 30 }}
      {{- with .Values.global.service.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.service.cerebrum.app.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.service.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if index .Values.global.service .Chart.Name "dependencies" }}
      initContainers:
        {{- range $depName, $dep := index .Values.global.service .Chart.Name "dependencies" }}
        - name: wait-for-{{ $depName }}
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z -w 2 {{ $dep.host | default (printf "%s.%s.svc.cluster.local" $depName $.Release.Namespace) }} {{ $dep.port }}; do
                echo "Waiting for {{ $depName }} to be ready..."
                sleep 2
              done
              echo "{{ $depName }} is ready!"
          resources:
            requests:
              cpu: "10m"
              memory: "16Mi"
            limits:
              cpu: "50m"
              memory: "32Mi"
        {{- end }}
      {{- end }}
      containers:
        - name: cerebrum
          envFrom:
            - secretRef:
                name: {{ .Values.global.service.secretName | quote }}
          image: {{ .Values.global.service.cerebrum.app.image }}:{{ .Values.global.service.cerebrum.app.tag | default .Values.global.service.tag }}
          imagePullPolicy: {{ .Values.global.service.imagePullPolicy | quote }}
          ports:
            - containerPort: {{ .Values.global.service.cerebrum.app.port | default 8000 }}
              name: cerebrum
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: cerebrum
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 15
          readinessProbe:
            httpGet:
              path: /health/ready
              port: cerebrum
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
          resources:
            {{- toYaml .Values.global.service.cerebrum.app.resources | default .Values.global.service.resources | nindent 12 }}
        - name: cerebrum-workers
          image: {{ .Values.global.service.cerebrum.sidecars.cerebrumWorkers.image }}:{{ .Values.global.service.cerebrum.sidecars.cerebrumWorkers.tag | default .Values.global.service.tag }}
          imagePullPolicy: {{ .Values.global.service.imagePullPolicy | quote }}
          envFrom:
            - secretRef:
                name: {{ .Values.global.service.secretName | quote }}
          resources:
            {{- toYaml .Values.global.service.cerebrum.app.resources | default .Values.global.service.resources | nindent 12 }}
{{- end }}