apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
  labels:
    app.kubernetes.io/name: hive-metastore
    app.kubernetes.io/component: hive-metastore
spec:
  ports:
    - name: thrift
      port: 9083
      protocol: TCP
  selector:
    app.kubernetes.io/name: hive-metastore
    app.kubernetes.io/component: hive-metastore
    app.kubernetes.io/instance: {{ .Release.Name | quote }}